=== AquariusPower/openMSX/share/hardwareconfig.dtd
<!ELEMENT msxconfig (device|config)+>
<!ELEMENT device (type,slotted?,parameter*,desc?,rem?)>
<!ATTLIST device
                 id CDATA #IMPLIED>
<!ELEMENT config (type,parameter*,desc?,rem?)>
<!ATTLIST config
                 id CDATA #IMPLIED>
<!-- config is like a device, but without a slotted,
     and should be used for non-device configuration -->
<!ELEMENT type (#PCDATA)>
<!ELEMENT slotted (page,ps,ss)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT ss (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
                    name CDATA #IMPLIED
                    class CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT rem (#PCDATA)>

=== AquariusPower/openMSX/share/machines/Sony_HB-201P/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "../../hardwareconfig.dtd">
<msxconfig>

  <info>
    <manufacturer>Sony</manufacturer>
    <code>HB-201P</code>
    <release_year>?</release_year>
    <description></description>
    <type>MSX</type>
  </info>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">false</parameter>
  </config>

  <device id="Main RAM">
    <type>RAM</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/hb-201p_basic-bios1.rom</parameter>
  </device>

  <device id="MSX Database">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/hb-201p_firmware.rom</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">TMS9929A</parameter>
  </device>

  <device id="PSG">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>
