=== AquariusPower/openMSX/share/romdb.dtd
<!ELEMENT romdb (rom)+>
<!ELEMENT rom (md5+,romtype)>
<!ATTLIST rom
              id CDATA #IMPLIED>
<!ELEMENT md5 (#PCDATA)+>
<!ELEMENT romtype (#PCDATA)>
<!ELEMENT crc32 (#PCDATA)*>
<!ELEMENT year (#PCDATA)?>
<!ELEMENT company (#PCDATA)?>
<!ELEMENT remark (#PCDATA)?>

=== AquariusPower/openMSX/share/romdb.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE romdb SYSTEM "romdb.dtd">
<romdb>

<!-- THE ORIGINAL DB -->
<!-- SOME ARE COMMENTED OUT TO PREVENT DOUBLES LATER ON -->

  <rom id="Bubbler">
    <sha1>6219ec49b735e80e3c8d1d5ba2bb107390df8716</sha1>
    <romtype>KONAMI5</romtype>
  </rom>
  <rom id="Painter">
    <sha1>7fd2a28c4fdaeb140f3c8c8fb90271b1472c97b9</sha1>
    <romtype>PLAIN</romtype>
  </rom>
  <rom id="Hydlide 2 (crack/modified?)">
    <sha1>552a758f77a7c35969523dbaca74587f0b59eb2b</sha1>
    <romtype>HYDLIDE2</romtype>
  </rom>
  <rom id="War of the Dead (crack/modified)">
    <sha1>eca36fe80a916eb6b196ec56edfc1296d793e350</sha1>
    <sha1>d452a79b25f18e6a6eadc5c592d5101f115ef0f0</sha1>
    <romtype>8kB</romtype>
  </rom>
  <rom id="Xevious (modified?)">
    <sha1>ab3f375b6890b2a9bb1b6124f0fa690950c749f2</sha1>
    <romtype>ASCII16</romtype>
  </rom>
  <rom id="Fantasy Zone II (modified?)">
    <sha1>1f39c472f1e02511fa7eaaf8ed9fcce4d45861b9</sha1>
    <romtype>ASCII16</romtype>
  </rom>
  <rom id="R-Type (modified?)">
    <sha1>9c886fff02779267041efe45dadefc5fd7f4b9a2</sha1>
    <romtype>RTYPE</romtype>
  </rom>
  <rom id="Strategic Mars (cracked?)">
    <sha1>58178e52855ce5ea365d8ce68c2020918e7513d4</sha1>
    <romtype>16kB</romtype>
  </rom>
  <rom id="Demonia">
    <sha1>d5b164797bc969b55c1a6f4006a4535c3fb03cf0</sha1>
    <romtype>8kB</romtype>
  </rom>
  <rom id="MSX AUDIO">
    <sha1>4061c461fa9ff21a6c0e46b3a71607e332d80ba3</sha1>
    <romtype>MSX-AUDIO</romtype>
  </rom>
  <rom id="Zemmix 126">
    <romtype>KOREAN126IN1</romtype>
    <sha1>3f0a7b0cbaa3d4c3c6ce744708c68c89eff82289</sha1>
    <company>Zemina</company>
    <remark></remark>
  </rom>
  <rom id="Game's 80">
    <romtype>KOREAN80IN1</romtype>
    <sha1>a4a75ed32c2af3c5f009661bb76be4f65e2e9a1f</sha1>
    <company>Zemina</company>
    <remark></remark>
  </rom>
  <rom id="MSX90-collection">
    <romtype>KOREAN90IN1</romtype>
    <sha1>edd109e4b518c41eb30a2b6f2a492598c9a08008</sha1>
    <company>Zemina</company>
    <remark></remark>
  </rom>
  <rom id="Zemmix 64">
    <romtype>KOREAN80IN1</romtype>
    <sha1>5f912637565932c2bd7c0d7b9be6ad3dc971f96f</sha1>
    <company>Zemina</company>
    <remark></remark>
  </rom>



<!-- THE NEW PART CONVERTED FROM JIROU KANEDA'S DB, MSX1 PART -->

  <rom id="10-Yard Fight">
    <romtype>PLAIN</romtype>
    <sha1>33536dac686b375ba13faf76a3baf2d6978904e0</sha1>
    <year>1986</year>
    <company>Irem</company>
    <remark></remark>
  </rom>
  <rom id="1942">
    <romtype>ASCII8</romtype>
    <sha1>0733cd627467a866846e15caf1770a5594eaf4cc</sha1>
    <year>1986</year>
    <company>Ascii</company>
    <remark></remark>
  </rom>
  <rom id="3D Golf Simulation - High-Speed Edition">
    <romtype>ROMBAS</romtype>
    <sha1>9a63d48c4fc05e76c9de25e5c5f2a0c99b5d1be4</sha1>
    <year>1984</year>
    <company>T&amp;E Soft</company>
    <remark></remark>
  </rom>
  <rom id="3D Golf Simulation - Normal Edition (1)">
    <romtype>ROMBAS</romtype>
    <sha1>f8164d3872b5d54eaeafc6de3bb98a472f0c828d</sha1>
    <year>1983</year>
    <company>T&amp;E Soft</company>
    <remark></remark>
  </rom>
  <rom id="3D Golf Simulation - Normal Edition (2)">
    <romtype>ROMBAS</romtype>
    <sha1>6fe8c1725c35d85a5e489c0c8d21134def09ecfb</sha1>
    <year>1983</year>
    <company>T&amp;E Soft</company>
    <remark></remark>
  </rom>
  <rom id="3D Tennis">
    <romtype>ROMBAS</romtype>
    <sha1>8f71dddd429173df7ce52c5245af1a76b482a901</sha1>
    <year>1983</year>
    <company>Ascii</company>
    <remark></remark>
  </rom>
  <rom id="A Life M36 Planet">
    <romtype>ASCII8</romtype>
    <sha1>6bde4e6761286a2909858ecef04155e17072996e</sha1>
    <year>1987</year>
    <company>Pixel</company>
    <remark></remark>
  </rom>
  <rom id="A.E.">
    <romtype>PLAIN</romtype>
    <sha1>6b8a684ddbadd798a8e599449b823bceca9cdb58</sha1>
    <year>1983</year>
    <company>Toshiba EMI</company>
    <remark></remark>
  </rom>
  <rom id="A1 Spirit">
    <romtype>KONAMI5</romtype>
    <sha1>937464eb371c68add2236bcef91d24a8ce7c4ed1</sha1>
    <year>1987</year>
    <company>Konami</company>
    <remark></remark>
  </rom>
  <rom id="Actman">
    <romtype>PLAIN</romtype>
    <sha1>cb48969f27eaebf24c61f651399ec2433d85bcbc</sha1>
    <year>1984</year>
    <company>Mass Tael</company>
    <remark></remark>
  </rom>
  <rom id="Adven'chuta!">
    <romtype>PLAIN</romtype>
    <sha1>ae0c0b0c9468e137eba5b52f96241acd55d9746a</sha1>
    <year>1983</year>
    <company>Mia</company>
    <remark></remark>
  </rom>
  <rom id="Alcazar">
    <romtype>PLAIN</romtype>
    <sha1>807676038cbba043b8099eba9c5840a4811a7e59</sha1>
    <year>1985</year>
    <company>Pony Canyon</company>
    <remark></remark>
  </rom>
  <rom id="Alibaba And 40 Thieves">
    <romtype>PLAIN</romtype>
    <sha1>639cb280544b060a618af23daf234a44baaf88de</sha1>
    <year>1984</year>
    <company>Sony</company>
    <remark></remark>
  </rom>
  <rom id="Alien 2">
    <romtype>ASCII16</romtype>
    <sha1>5380e913d8dac23470446844cab21f6921101af8</sha1>
    <year>1987</year>
    <company>Square</company>
    <remark></remark>
  </rom>
  <rom id="Alien 8">
    <romtype>PLAIN</romtype>
    <sha1>5fb90be078e432db92dd39e621d12f612dbea4a8</sha1>
    <year>1986</year>
    <company>Jaleco</company>
    <remark></remark>
  </rom>
  <rom id="Alpha Roid">
    <romtype>PLAIN</romtype>
    <sha1>97e7d0ee40c7d6ce1a8edf7b06e5014e6745cfda</sha1>
    <year>1986</year>
    <company>Pony Canyon</company>
    <remark></remark>
  </rom>
  <rom id="Alpha Squadron">
    <romtype>PLAIN</romtype>
    <sha1>1d81e6cc165b3330b9b3c8b4f4da0417b1ab901e</sha1>
    <year>1984</year>
    <company>Sony</company>
    <remark></remark>
  </rom>
  <rom id="American Truck (1)">
    <romtype>PLAIN</romtype>
    <sha1>076abc988d51faef30143750dd41318a8a48c5c4</sha1>
    <year>1985</year>
    <company>Telenet</company>
    <remark></remark>
  </rom>
  <rom id="American Truck (2)">
    <romtype>PLAIN</romtype>
    <sha1>88fa967c420f7090a11e5de1d3674f4527f53d52</sha1>
    <year>1985</year>
    <company>Telenet</company>
    <remark></remark>
  </rom>
  <rom id="Anaza">
    <romtype>PLAIN</romtype>
    <sha1>27c40ec7013c1ad1f9a7e1ac1e0c8be99f1e703f</sha1>
    <year>1987</year>
    <company>Hot-B</company>
    <remark></remark>
  </rom>
  <rom id="Angelo">
    <romtype>PLAIN</romtype>
    <sha1>a1abfc53a36d387b9f0687e3f5897c1ebdf21517</sha1>
    <year>1984</year>
    <company>Mass Tael</company>
    <remark></remark>
  </rom>
  <rom id="Animal Land Satsujin Jiken">
    <romtype>ASCII8</romtype>
    <sha1>495876c504bdc4de24860ea15b25dda8f3b06c49</sha1>
    <year>1987</year>
    <company>Enix</company>
    <remark></remark>
  </rom>
  <rom id="Antarctic Adventure">
    <romtype>PLAIN</romtype>
    <sha1>e894a38f3e2ad435cc5d17a66600e6016b5e47fb</sha1>
    <year>1984</year>
    <company>Konami</company>
    <remark></remark>
  </rom>
  <rom id="Anty">
    <romtype>PLAIN</romtype>
    <sha1>f236345f43828597739f4a326318b6a3876ff73f</sha1>
    <year>1984</year>
    <company>Bothtec</company>
    <remark></remark>
  </rom>
  <rom id="Aquapolis SOS">
    <romtype>PLAIN</romtype>
    <sha1>633cb458eeab0fea59a70a9a620b7783a44eb0a6</sha1>
    <year>1983</year>
    <company>Paxon</company>
    <remark></remark>
  </rom>
  <rom id="Aquattack">
    <romtype>PLAIN</romtype>
    <sha1>93462ac9a322c2e5e0d996fddbe9eba2f3436931</sha1>
    <year>1984</year>
    <company>Toshiba EMI</company>
    <remark></remark>
  </rom>
  <rom id="Aramo">
    <romtype>PLAIN</romtype>
    <sha1>ec53d72e41e114574f4c116cab19e1633f3da207</sha1>
    <year>1986</year>
    <company>Sein</company>
    <remark></remark>
  </rom>
  <rom id="Arkanoid">
    <romtype>PLAIN</romtype>
    <sha1>2183f07fa3ba87360100b2fa21fda0f55c0f8814</sha1>
    <year>1986</year>
    <company>Taito</company>
    <remark></remark>
  </rom>
  <rom id="Arubatoros">
    <romtype>PLAIN</romtype>
    <sha1>ec5111e3b06d64ef51196ff87448e1c62be4cdd8</sha1>
    <year>1986</year>
    <company>Telenet</company>
    <remark></remark>
  </rom>
  <rom id="Athletic Ball">
    <romtype>PLAIN</romtype>
    <sha1>fbe43d67a5bc0aedb2e194a4e5f9497b7488362b</sha1>
    <year>1984</year>
    <company>Ascii</company>
    <remark></remark>
  </rom>
  <rom id="Athletic Land (2)">
    <romtype>PLAIN</romtype>
    <sha1>90bdd12d632d2e909ac5d69235ad0366f430b734</sha1>
    <year>1984</year>
    <company>Konami</company>
    <remark></remark>
  </rom>
  <rom id="Athletic Land (1)">
    <romtype>PLAIN</romtype>
    <sha1>866cb3ab10f17e4fb356fbd7277bbf17c4e27ebe</sha1>
    <year>1984</year>
    <company>Konami</company>
    <remark></remark>
  </rom>
  <rom id="Attack 4 Women Volleyball">
    <romtype>PLAIN</romtype>
    <sha1>c5f1897c416f62cd58cd6257282e3428155cd698</sha1>
    <year>1986</year>
    <company>Pax</company>
    <remark></remark>
  </rom>
  <rom id="B.C's Quest">
    <romtype>PLAIN</romtype>
    <sha1>4c8a97669017296c2360ff9d53694a292197991e</sha1>
    <year>1985</year>
    <company>Toshiba EMI</company>
    <remark></remark>
  </rom>
  <rom id="Back To The Future">
    <romtype>PLAIN</romtype>
    <sha1>469b07eef08348c9acc14e63ba0cd35aef236983</sha1>
    <year>1985</year>
    <company>Pony Canyon</company>
    <remark></remark>
  </rom>
  <rom id="Back Gammon (1)">
    <romtype>PLAIN</romtype>
    <sha1>2b8878609bcc0d1555ae250d621ba6e9df4afc52</sha1>
    <year>1984</year>
    <company>Sony</company>
    <remark></remark>
  </rom>
  <rom id="Back Gammon (2)">
    <romtype>PLAIN</romtype>
    <sha1>c345357e71d1b8f2c9663bf28abb5a3a2957d49f</sha1>
    <year>1984</year>
    <company>Sony</company>
    <remark></remark>
  </rom>
  <rom id="Balance (2)">
    <romtype>PLAIN</romtype>
    <sha1>cd452442338366411f6b24739fe59e20f3ac24dc</sha1>
    <year>1984</year>
    <company>Hal</company>
    <remark></remark>
  </rom>
  <rom id="Balance (1)">
    <romtype>PLAIN</romtype>
    <sha1>6d73ee99ac367a2558fd9366af75ad39ed0d4e69</sha1>
