=== AquariusPower/openMSX/src/msxconfig.dtd
<!ELEMENT msxconfig (device)+>
<!ELEMENT device (type,slotted?,parameter+)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT slotted (page,ps,ss)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT ss (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
                    name CDATA #IMPLIED>

=== AquariusPower/openMSX/share/extensions/pac/hardwareconfig.xml
<?xml version="1.0" ?>
<!-- $Id$ --><!DOCTYPE msxconfig
  SYSTEM 'msxconfig.dtd'>
<msxconfig>
  <device id="PanaSoft SW-M001 PAC">
    <type>PAC</type>
    <slotted><ps>-1</ps><ss>-1</ss><page>1</page></slotted>
    <sramname>pac.pac</sramname>
  </device>
</msxconfig>

=== AquariusPower/openMSX/src/cfg/nms8250-FDC.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">Philips</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>0</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>2</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>3</page>
    </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">128</parameter>
  </device>

  <device id="biosrom">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-bios.rom</parameter>
  </device>

  <device id="basicrom">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-basic.rom</parameter>
  </device>

  <device id="subrom">
    <type>Rom</type>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-sub.rom</parameter>
  </device>

  <!-- 
  <device id="diskrom">
    <type>Rom</type>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-disk.rom</parameter>
    <parameter name="" class="patchcode">MSXDiskRomPatch</parameter>

    <parameter name="0x0010" class="patch">0xED</parameter>
    <parameter name="0x0011" class="patch">0xFE</parameter>
    <parameter name="0x0012" class="patch">0xC9</parameter>
    <parameter name="0x0013" class="patch">0xED</parameter>
    <parameter name="0x0014" class="patch">0xFE</parameter>
    <parameter name="0x0015" class="patch">0xC9</parameter>
    <parameter name="0x0016" class="patch">0xED</parameter>
    <parameter name="0x0017" class="patch">0xFE</parameter>
    <parameter name="0x0018" class="patch">0xC9</parameter>
    <parameter name="0x001C" class="patch">0xED</parameter>
    <parameter name="0x001D" class="patch">0xFE</parameter>
    <parameter name="0x001E" class="patch">0xC9</parameter>
    <parameter name="0x001F" class="patch">0xED</parameter>
    <parameter name="0x0020" class="patch">0xFE</parameter>
    <parameter name="0x0021" class="patch">0xC9</parameter>

    <parameter name="0x3FF8" class="patch">0x24</parameter>
    <parameter name="0x3FF9" class="patch">0x00</parameter>
    <parameter name="0x3FFA" class="patch">0x07</parameter>
    <parameter name="0x3FFB" class="patch">0x00</parameter>
    <parameter name="0x3FFC" class="patch">0xFE</parameter>
    <parameter name="0x3FFD" class="patch">0xFC</parameter>
  </device>
  -->

  <device id="Memmory Mapped FDC">
    <type>FDC</type>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>2</page>
    </slotted>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="filename">cfg/nms8250-disk.rom</parameter>
    <parameter name="chip">2793</parameter>
    <parameter name="drivename1">diska</parameter>
    <parameter name="interface">memory</parameter>
  </device>

  <!--
  <config id="diska">
    <parameter name="filename">PSYCHO.DSK</parameter>
  </config>
  -->

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9938</parameter>
    <parameter name="limit_sprites">true</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <config id="renderer">
    <type>SDLHi</type>
    <parameter name="full_screen">false</parameter>
  </config>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="load">true</parameter>
    <parameter name="save">true</parameter>
    <parameter name="filename">RTC.SAVE</parameter>
  </device>

  <config id="RealTime">
    <parameter name="sync_interval">50</parameter>
    <parameter name="max_catch_up_time">2000</parameter>
    <parameter name="max_catch_up_factor">105</parameter>
  </config>

  <!--
  <device id="Penguin Adventure Cartridge">
    <type>Rom</type>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>2</page>
    </slotted>
    <parameter name="filename">NEMESIS2.ROM</parameter>
    <parameter name="skip_headerbytes">0</parameter>
    <parameter name="volume">11500</parameter>
  </device>
  -->

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <config id="Mixer">
    <parameter name="frequency">22050</parameter>
    <parameter name="samples">512</parameter>
  </config>

  <config id="Console">
    <parameter name="font">ConsoleFont.bmp</parameter>
    <parameter name="background">ConsoleBackground.bmp</parameter>
  </config>

</msxconfig>

=== AquariusPower/openMSX/src/cfg/cbios-msx2.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">Philips</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">512</parameter>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>0</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>2</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>3</page>
    </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
  </device>

  <device id="biosrom">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">../Contrib/cbios/MSXB.BIN</parameter>
  </device>

  <device id="biosrom2">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">../Contrib/cbios/MSXB_SH.BIN</parameter>
  </device>

  <device id="subrom">
    <type>Rom</type>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">../Contrib/cbios/MSXB_SUB.BIN</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9938</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <config id="renderer">
    <type>SDLHi</type>
    <parameter name="full_screen">false</parameter>
  </config>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">RTC.SAVE</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

</msxconfig>

=== AquariusPower/openMSX/share/machines/National_FS-5500F1/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <info>
    <manufacturer>National</manufacturer>
    <code>FS-5500F1</code>
    <release_year>1985</release_year>
    <description></description>
    <type>MSX2</type>
  </info>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">true</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="Main RAM">
    <type>RAM</type>
    <slotted> <ps>3</ps> <ss>2</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/fs-5500_basic-bios2.rom</parameter>
  </device>

  <device id="MSX Sub ROM">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <parameter name="filename">roms/fs-5500_msx2sub.rom</parameter>
  </device>

  <device id="Super Impose">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/fs-5500_superimp.rom</parameter>
  </device>

  <device id="MSX Kanji Driver">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/fs-5500_kanjibasic.rom</parameter>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">roms/fs-5500_kanjifont.rom</parameter>
  </device>

  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/fs-5500_disk.rom</parameter>
    <parameter name="type">MB8877A</parameter>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="drivename1">diska</parameter>
  </device>

  <device id="S1985">
    <type>S1985</type>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9938</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <device id="PSG">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
    <parameter name="keyboardlayout">50on</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="sramname">fs-5500f1.cmos</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>

=== AquariusPower/openMSX/share/machines/Sanyo_PHC-35J/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <info>
    <manufacturer>Sanyo</manufacturer>
    <code>PHC-35J</code>
    <release_year>1989</release_year>
    <description></description>
    <type>MSX2+</type>
  </info>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <config id="RenShaTurbo">
     <parameter name="min_ints">47</parameter>
     <parameter name="max_ints">221</parameter>
  </config>

  <config id="MapperType">
    <parameter name="type">Philips</parameter>
  </config>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">64</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/phc-35j_basic-bios2p.rom</parameter>
  </device>

  <device id="MSX Sub ROM">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>0</page> </slotted>
    <parameter name="filename">roms/phc-35j_msx2psub.rom</parameter>
  </device>

  <device id="MSX Kanji Driver with BASIC">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/phc-35j_kanjibasic.rom</parameter>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">roms/phc-35j_kanjifont.rom</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9958</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <device id="PSG">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
    <parameter name="keyboardlayout">JIS</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="sramname">phc-35j.cmos</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <device id="F4Device">
    <type>F4Device</type>
    <parameter name="inverted">true</parameter>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>

=== AquariusPower/openMSX/share/machines/Panasonic_FS-A1FX/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <config id="RenShaTurbo">
     <parameter name="min_ints">47</parameter>
     <parameter name="max_ints">221</parameter>
  </config>

  <config id="MapperType">
    <parameter name="type">Philips</parameter>
  </config>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">64</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/fs-a1fx_basic-bios2p.rom</parameter>
  </device>

  <device id="MSX Sub ROM">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>0</page> </slotted>
    <parameter name="filename">roms/fs-a1fx_msx2psub.rom</parameter>
  </device>

  <device id="A1 Cockpit">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/fs-a1fx_cockpit.rom</parameter>
  </device>

  <device id="MSX Kanji Driver with BASIC">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/fs-a1fx_kanjibasic.rom</parameter>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">roms/fs-a1fx_kanjifont.rom</parameter>
  </device>

  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted> <ps>3</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/fs-a1fx_disk.rom</parameter>
    <parameter name="type">TC8566AF</parameter>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="drivename1">diska</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9958</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <device id="PSG">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="sramname">fs-a1fx.cmos</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <device id="F4Device">
    <type>F4Device</type>
    <parameter name="inverted">true</parameter>
  </device>

  <device id="Switch">
    <type>Matsushita</type>
    <parameter name="sramname">fs-a1fx.sram</parameter>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>

=== AquariusPower/openMSX/share/extensions/ram4mb/hardwareconfig.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  <device id="4MB External RAM">
    <type>MemoryMapper</type>
    <slotted><ps>-1</ps><ss>-1</ss><page>0</page></slotted>
    <slotted><ps>-1</ps><ss>-1</ss><page>1</page></slotted>
    <slotted><ps>-1</ps><ss>-1</ss><page>2</page></slotted>
    <slotted><ps>-1</ps><ss>-1</ss><page>3</page></slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">4096</parameter>
  </device>
</msxconfig>

=== AquariusPower/openMSX/src/msxconfigFDC.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="MotherBoard">
    <type>MotherBoard</type>
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <!--
  <device id="PrinterPort">
    <type>PrinterPort</type>
    <parameter name="logfile">printport.log</parameter>
  </device>
  -->

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">Philips</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>0</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>2</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>2</ss>
      <page>3</page>
    </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">128</parameter>
  </device>

  <device id="biosrom">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-bios.rom</parameter>
  </device>

  <device id="basicrom">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-basic.rom</parameter>
  </device>

  <device id="subrom">
    <type>Rom</type>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-sub.rom</parameter>
  </device>

<!--
  <device id="diskrom">
    <type>Rom</type>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-disk.rom</parameter>
    <parameter name="" class="patchcode">MSXDiskRomPatch</parameter>

    <parameter name="0x0010" class="patch">0xED</parameter>
    <parameter name="0x0011" class="patch">0xFE</parameter>
    <parameter name="0x0012" class="patch">0xC9</parameter>
    <parameter name="0x0013" class="patch">0xED</parameter>
    <parameter name="0x0014" class="patch">0xFE</parameter>
    <parameter name="0x0015" class="patch">0xC9</parameter>
    <parameter name="0x0016" class="patch">0xED</parameter>
    <parameter name="0x0017" class="patch">0xFE</parameter>
    <parameter name="0x0018" class="patch">0xC9</parameter>
    <parameter name="0x001C" class="patch">0xED</parameter>
    <parameter name="0x001D" class="patch">0xFE</parameter>
    <parameter name="0x001E" class="patch">0xC9</parameter>
    <parameter name="0x001F" class="patch">0xED</parameter>
    <parameter name="0x0020" class="patch">0xFE</parameter>
    <parameter name="0x0021" class="patch">0xC9</parameter>

    <parameter name="0x3FF8" class="patch">0x24</parameter>
    <parameter name="0x3FF9" class="patch">0x00</parameter>
    <parameter name="0x3FFA" class="patch">0x07</parameter>
    <parameter name="0x3FFB" class="patch">0x00</parameter>
    <parameter name="0x3FFC" class="patch">0xFE</parameter>
    <parameter name="0x3FFD" class="patch">0xFC</parameter>
  </device>
-->
  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>2</page>
    </slotted>
    <parameter name="filename">cfg/nms8250-disk.rom</parameter>
    <parameter name="type">Philips</parameter>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="drivename1">diska</parameter>
    <parameter name="drivename2">diskb</parameter>
  </device>

<!--
  <device id="MSX-Audio">
    <type>Audio</type>
    <parameter name="volume">20000</parameter>
    <parameter name="mode">right</parameter>
  </device>

  <device id="FM PAC">
    <type>FM-PAC</type>
    <slotted>
      <ps>2</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">FMPAC.ROM</parameter>
    <parameter name="volume">20000</parameter>
    <parameter name="mode">left</parameter>
    <parameter name="load">true</parameter>
    <parameter name="save">true</parameter>
    <parameter name="sramname">FMPAC.PAC</parameter>
  </device>
-->

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9938</parameter>
    <parameter name="limit_sprites">true</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <config id="renderer">
    <type>SDLHi</type>
    <parameter name="full_screen">false</parameter>
  </config>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="load">true</parameter>
    <parameter name="save">true</parameter>
    <parameter name="filename">RTC.SAVE</parameter>
  </device>

  <config id="RealTime">
    <type>RealTime</type>
    <parameter name="sync_interval">50</parameter>
    <parameter name="max_catch_up_time">1500</parameter>
    <parameter name="max_catch_up_factor">105</parameter>
  </config>

  <!--
  <device id="Penguin Adventure Cartridge">
    <type>Rom</type>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>2</page>
    </slotted>
    <parameter name="filename">NEMESIS2.ROM</parameter>
    <parameter name="filesize">auto</parameter>
    <parameter name="skip_headerbytes">0</parameter>
    <parameter name="volume">11500</parameter>
    <parameter name="mappertype">2</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">GAME.SRAM</parameter>
  </device>
  -->

  <device id="cpu">
    <type>CPU</type>
  </device>

  <config id="Mixer">
    <type>Mixer</type>
    <parameter name="frequency">22050</parameter>
    <parameter name="samples">512</parameter>
  </config>
  <!-- replaced with the SearchPaths section below
  <config id="rompath">
    <type>rompath</type>
    <parameter name="separator">/</parameter>
    <parameter name="1" class="path">ROMS</parameter>
    <parameter name="2" class="path">TAPES</parameter>
    <parameter name="3" class="path">DISKS</parameter>
  </config>
  -->

  <config id="SearchPaths">
    <parameter class="disk">disks</parameter>
    <parameter class="rom">roms</parameter>
    <parameter class="rom">cfg</parameter>
    <parameter class="tape">tapes</parameter>
    <parameter class="config">cfg</parameter>
    <parameter class="state">cfg</parameter>
  </config>

  <config id="Console">
    <type>Console</type>
    <parameter name="font">ConsoleFont.png</parameter>
    <parameter name="background">ConsoleBackground.bmp</parameter>
  </config>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>

  </config>

</msxconfig>
