=== AquariusPower/openMSX/src/msxconfig.dtd
<!ELEMENT msxconfig (device)+>
<!ELEMENT device (type,slotted?,parameter+)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT slotted (page,ps,ss)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT ss (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
                    name CDATA #IMPLIED>

=== AquariusPower/openMSX/src/cfg/Panasonic_FS-A1GT.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">true</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">TurboR</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">512</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">fs-a1gt_basic-biostr.rom</parameter>
  </device>

  <device id="MSX Sub ROM">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>0</page> </slotted>
    <parameter name="filename">fs-a1gt_msxtrsub.rom</parameter>
  </device>

  <device id="MSX Music">
    <type>Music</type>
    <slotted> <ps>0</ps> <ss>2</ss> <page>1</page> </slotted>
    <parameter name="filename">fs-a1gt_fmbasic.rom</parameter>
    <parameter name="volume">9000</parameter>   
    <parameter name="mode">mono</parameter>
  </device>
  
  <device id="MSX Opening ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>3</ss> <page>1</page> </slotted>
    <parameter name="filename">fs-a1gt_msxtropt.rom</parameter>
  </device>

  <device id="FS-A1GT">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>3</page> </slotted>
    <parameter name="filename">fs-a1gt_firmware.rom</parameter>
    <parameter name="mappertype">PANASONIC</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">fs-a1gt.sram</parameter>
  </device>

  <device id="MSX Kanji Driver with BASIC">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <parameter name="filename">fs-a1gt_kanjibasic.rom</parameter>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">fs-a1gt_kanjifont.rom</parameter>
  </device>

  <device id="S1990">
    <type>S1990</type>
  </device>

  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted> <ps>3</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>2</page> </slotted>
    <parameter name="filename">fs-a1gt_msxdos23.rom</parameter>
    <parameter name="type">Panasonic</parameter>
    <parameter name="" class="patchcode">MSXDiskRomPatch</parameter>
    <parameter name="0x3FF0" class="patch">0x00</parameter>
    <parameter name="0x3FF1" class="patch">0x33</parameter>
    <parameter name="0x3FF2" class="patch">0xFF</parameter>
    <parameter name="0x3FF3" class="patch">0xFF</parameter>
    <parameter name="0x3FF4" class="patch">0x80</parameter>
    <parameter name="0x3FF5" class="patch">0x00</parameter>
    <parameter name="0x3FF6" class="patch">0xFF</parameter>
    <parameter name="0x3FF7" class="patch">0xFF</parameter>
    <parameter name="0x3FF8" class="patch">0xFF</parameter>
    <parameter name="0x3FF9" class="patch">0xFF</parameter>
    <parameter name="0x3FFA" class="patch">0xFF</parameter>
    <parameter name="0x3FFB" class="patch">0xFF</parameter>
    <parameter name="0x3FFC" class="patch">0xFC</parameter>
    <parameter name="0x3FFD" class="patch">0xFC</parameter>
    <parameter name="0x3FFE" class="patch">0xFF</parameter>
    <parameter name="0x3FFF" class="patch">0x3F</parameter>
    <parameter name="0x7FF0" class="patch">0x01</parameter>
    <parameter name="0x7FF1" class="patch">0x33</parameter>
    <parameter name="0x7FF2" class="patch">0xFF</parameter>
    <parameter name="0x7FF3" class="patch">0xFF</parameter>
    <parameter name="0x7FF4" class="patch">0x80</parameter>
    <parameter name="0x7FF5" class="patch">0x00</parameter>
    <parameter name="0x7FF6" class="patch">0xFF</parameter>
    <parameter name="0x7FF7" class="patch">0xFF</parameter>
    <parameter name="0x7FF8" class="patch">0xFF</parameter>
    <parameter name="0x7FF9" class="patch">0xFF</parameter>
    <parameter name="0x7FFA" class="patch">0xFF</parameter>
    <parameter name="0x7FFB" class="patch">0xFF</parameter>
    <parameter name="0x7FFC" class="patch">0xFC</parameter>
    <parameter name="0x7FFD" class="patch">0xFC</parameter>
    <parameter name="0x7FFE" class="patch">0xFF</parameter>
    <parameter name="0x7FFF" class="patch">0x3F</parameter>
    <parameter name="0xBFF0" class="patch">0x02</parameter>
    <parameter name="0xBFF1" class="patch">0x33</parameter>
    <parameter name="0xBFF2" class="patch">0xFF</parameter>
    <parameter name="0xBFF3" class="patch">0xFF</parameter>
    <parameter name="0xBFF4" class="patch">0x80</parameter>
    <parameter name="0xBFF5" class="patch">0x00</parameter>
    <parameter name="0xBFF6" class="patch">0xFF</parameter>
    <parameter name="0xBFF7" class="patch">0xFF</parameter>
    <parameter name="0xBFF8" class="patch">0xFF</parameter>
    <parameter name="0xBFF9" class="patch">0xFF</parameter>
    <parameter name="0xBFFA" class="patch">0xFF</parameter>
    <parameter name="0xBFFB" class="patch">0xFF</parameter>
    <parameter name="0xBFFC" class="patch">0xFC</parameter>
    <parameter name="0xBFFD" class="patch">0xFC</parameter>
    <parameter name="0xBFFE" class="patch">0xFF</parameter>
    <parameter name="0xBFFF" class="patch">0x3F</parameter>
    <parameter name="0xFFF0" class="patch">0x03</parameter>
    <parameter name="0xFFF1" class="patch">0x33</parameter>
    <parameter name="0xFFF2" class="patch">0xFF</parameter>
    <parameter name="0xFFF3" class="patch">0xFF</parameter>
    <parameter name="0xFFF4" class="patch">0x80</parameter>
    <parameter name="0xFFF5" class="patch">0x00</parameter>
    <parameter name="0xFFF6" class="patch">0xFF</parameter>
    <parameter name="0xFFF7" class="patch">0xFF</parameter>
    <parameter name="0xFFF8" class="patch">0xFF</parameter>
    <parameter name="0xFFF9" class="patch">0xFF</parameter>
    <parameter name="0xFFFA" class="patch">0xFF</parameter>
    <parameter name="0xFFFB" class="patch">0xFF</parameter>
    <parameter name="0xFFFC" class="patch">0xFC</parameter>
    <parameter name="0xFFFD" class="patch">0xFC</parameter>
    <parameter name="0xFFFE" class="patch">0xFF</parameter>
    <parameter name="0xFFFF" class="patch">0x3F</parameter>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="drivename1">diska</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9958</parameter>
    <parameter name="limit_sprites">true</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="load">true</parameter>
    <parameter name="save">true</parameter>
    <parameter name="filename">fs-a1gt.cmos</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>
  
  <device id="Turbo-R timer">
    <type>E6Timer</type>
  </device>
  
  <device id="F4Device">
    <type>F4Device</type>
    <parameter name="inverted">false</parameter>
  </device>

  <device id="TurboRLeds">
    <type>TurboRLeds</type>
  </device>

  <device id="TurboRPause">
    <type>TurboRPause</type>
  </device>

  <device id="PCM">
    <type>TurboRPCM</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="MSX-Midi">
    <type>MSX-Midi</type>
  </device>

  <device id="Switch">
    <type>Matsushita</type>
    <parameter name="loadsram">false</parameter>
    <parameter name="savesram">false</parameter>
    <parameter name="sramname">fs-a1gt.sram</parameter>
  </device>

</msxconfig>

=== AquariusPower/openMSX/share/extensions/ide/hardwareconfig.xml
<?xml version="1.0" ?>
<!-- $Id$ --><!DOCTYPE msxconfig
  SYSTEM 'msxconfig.dtd'>
<msxconfig>

  <device id="Sunrise IDE">
    <type>SunriseIDE</type>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>0</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>1</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>2</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>3</page> </slotted>
    <filename>roms/ide221.dat</filename>
    <master>myHD</master>
  </device>

  <config id="myHD">
    <type>IDEHD</type>
    <filename>hd.dsk</filename>
    <size>100</size>
  </config>

</msxconfig>

=== AquariusPower/openMSX/src/cfg/TurboR-GT.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="SearchPaths">
    <parameter class="disk">disks</parameter>
    <parameter class="rom">roms</parameter>
    <parameter class="rom">cfg</parameter>
    <parameter class="tape">tapes</parameter>
    <parameter class="config">cfg</parameter>
    <parameter class="state">cfg</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">true</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">TurboR</parameter>
  </device>

  <device id="biosrom">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <parameter name="filename">TurboR-GT-bios.rom</parameter>
  </device>

  <device id="basicrom">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">TurboR-GT-basic.rom</parameter>
  </device>

  <device id="MSX Music">
    <type>Music</type>
    <slotted> <ps>0</ps> <ss>2</ss> <page>1</page> </slotted>
    <parameter name="filename">TurboR-GT-music.rom</parameter>
    <parameter name="volume">9000</parameter>
    <parameter name="mode">mono</parameter>
  </device>
  
  <device id="MSX Opening ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>3</ss> <page>1</page> </slotted>
    <parameter name="filename">MSXTROPT.ROM</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">512</parameter>
  </device>

  <device id="subrom">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>0</page> </slotted>
    <parameter name="filename">TurboR-GT-sub.rom</parameter>
  </device>
  
  <device id="kanji basic">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <parameter name="filename">TurboR-GT-kanji.rom</parameter>
  </device>

  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted> <ps>3</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>2</page> </slotted>
    <parameter name="filename">MSXDOS-2.3.rom</parameter>
    <parameter name="type">TurboR</parameter>
    <parameter name="drivename1">diska</parameter>
  </device>

  <device id="MSX VIEW">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>2</page> </slotted>
    <parameter name="filename">TurboR-GT-4MB.rom</parameter>
    <parameter name="mappertype">PANASONIC</parameter>
    <parameter name="loadsram">false</parameter>
    <parameter name="savesram">false</parameter>
  </device>
  
  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9958</parameter>
    <parameter name="limit_sprites">true</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <config id="renderer">
    <type>SDLGL</type>
    <parameter name="full_screen">false</parameter>
  </config>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="load">true</parameter>
    <parameter name="save">true</parameter>
    <parameter name="filename">RTC.SAVE</parameter>
  </device>

  <config id="RealTime">
    <parameter name="sync_interval">50</parameter>
    <parameter name="max_catch_up_time">2000</parameter>
    <parameter name="max_catch_up_factor">105</parameter>
  </config>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>
  
  <device id="Turbo-R timer">
    <type>E6Timer</type>
  </device>
  
  <device id="F4Device">
    <type>F4Device</type>
    <parameter name="inverted">false</parameter>
  </device>

  <device id="TurboRLeds">
    <type>TurboRLeds</type>
  </device>

  <device id="TurboRPause">
    <type>TurboRPause</type>
  </device>
  
  <device id="S1990">
    <type>S1990</type>
  </device>
  
  <device id="PCM">
    <type>TurboRPCM</type>
    <parameter name="volume">21000</parameter>
  </device>

  <config id="Mixer">
    <parameter name="frequency">22050</parameter>
    <parameter name="samples">512</parameter>
  </config>

  <config id="Console">
    <parameter name="font">ConsoleFont.png</parameter>
    <parameter name="background">ConsoleBackground2.png</parameter>
  </config>

</msxconfig>

=== AquariusPower/openMSX/share/machines/Canon_V-20/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

<config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">3-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">false</parameter>
  </config>

  <device id="Main RAM">
    <type>RAM</type>
    <slotted> <ps>2</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>2</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>2</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>2</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/v-20_basic-bios1.rom</parameter>
        <parameter name="0x00E1" class="patch">0xED</parameter>
    <parameter name="0x00E2" class="patch">0xFE</parameter>
    <parameter name="0x00E3" class="patch">0xC9</parameter>
    <parameter name="0x00E4" class="patch">0xED</parameter>
    <parameter name="0x00E5" class="patch">0xFE</parameter>
    <parameter name="0x00E6" class="patch">0xC9</parameter>
    <parameter name="0x00E7" class="patch">0xED</parameter>
    <parameter name="0x00E8" class="patch">0xFE</parameter>
    <parameter name="0x00E9" class="patch">0xC9</parameter>
    <parameter name="0x00EA" class="patch">0xED</parameter>
    <parameter name="0x00EB" class="patch">0xFE</parameter>
    <parameter name="0x00EC" class="patch">0xC9</parameter>
    <parameter name="0x00ED" class="patch">0xED</parameter>
    <parameter name="0x00EE" class="patch">0xFE</parameter>
    <parameter name="0x00EF" class="patch">0xC9</parameter>
    <parameter name="0x00F0" class="patch">0xED</parameter>
    <parameter name="0x00F1" class="patch">0xFE</parameter>
    <parameter name="0x00F2" class="patch">0xC9</parameter>
    <parameter name="0x00F3" class="patch">0xED</parameter>
    <parameter name="0x00F4" class="patch">0xFE</parameter>
    <parameter name="0x00F5" class="patch">0xC9</parameter>
    <parameter name="" class="patchcode">MSXTapePatch</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">TMS9929A</parameter>
  </device>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>

=== AquariusPower/openMSX/share/extensions/mbstereo/hardwareconfig.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  <device id="FM PAC">
    <type>FM-PAC</type>
    <slotted><ps>-1</ps><ss>-1</ss><page>1</page></slotted>
    <parameter name="filename">roms/FMPAC.ROM</parameter>
    <parameter name="volume">13000</parameter>
    <parameter name="mode">left</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">FMPAC.PAC</parameter>
  </device>
  <device id="MSX-Audio-1">
    <type>Audio</type>
    <parameter name="volume">12000</parameter>
    <parameter name="mode">right</parameter>
    <parameter name="sampleram">256</parameter>
  </device>
  <device id="MSX-Audio-Midi">
    <type>Audio-Midi</type>
  </device>
</msxconfig>

=== AquariusPower/openMSX/share/machines/Sanyo_PHC-70FD2/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">Philips</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted> <ps>3</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">64</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/phc-70fd2_basic-bios2p.rom</parameter>
  </device>

  <device id="MSX Sub ROM">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>0</page> </slotted>
    <parameter name="filename">roms/phc-70fd2_msx2psub.rom</parameter>
  </device>

  <device id="MSX Music">
    <type>Music</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/phc-70fd2_fmbasic.rom</parameter>
    <parameter name="volume">9000</parameter>   
    <parameter name="mode">mono</parameter>
  </device>

  <device id="BASIC Compiler">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/phc-70fd2_basickun.rom</parameter>
  </device>

  <device id="MSX Kanji Driver with BASIC">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/phc-70fd2_kanjibasic.rom</parameter>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">roms/phc-70fd2_kanjifont.rom</parameter>
  </device>

  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted> <ps>3</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/phc-70fd2_disk.rom</parameter>
    <parameter name="type">TC8566AF</parameter>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="drivename1">diska</parameter>
    <parameter name="drivename2">diskb</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9958</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="sramname">phc-70fd2.cmos</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <device id="F4Device">
    <type>F4Device</type>
    <parameter name="inverted">true</parameter>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>

=== AquariusPower/openMSX/share/extensions/Toshiba_HX-MU900/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  <device id="Toshiba HX-MU900 MSX-Audio">
    <type>Audio</type>
    <parameter name="volume">12000</parameter>
    <parameter name="mode">mono</parameter>
    <!-- <parameter name="sampleram">32</parameter> -->
  </device>
  
  <device id="Toshiba HX-MU900 firmware">
    <type>Rom</type>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>1</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>2</page> </slotted>
    <parameter name="filename">roms/hx-mu900.rom</parameter>
  </device>
  
</msxconfig>

=== AquariusPower/openMSX/share/machines/National_FS-4600/hardwareconfig.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">true</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>

  <device id="MapperIO">
    <type>MapperIO</type>
    <parameter name="type">Philips</parameter>
  </device>

  <device id="Main RAM">
    <type>MemoryMapper</type>
    <slotted> <ps>3</ps> <ss>2</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>2</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">128</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">fs-4600_basic-bios2.rom</parameter>
  </device>

  <device id="MSX Sub ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>1</ss> <page>0</page> </slotted>
    <parameter name="filename">fs-4600_msx2sub.rom</parameter>
  </device>

  <device id="Word Font 1">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>2</ss> <page>0</page> </slotted>
    <parameter name="filename">fs-4600_wordfont1.rom</parameter>
  </device>

  <device id="Word Font 2">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>3</ss> <page>0</page> </slotted>
    <parameter name="filename">fs-4600_wordfont2.rom</parameter>
  </device>

  <device id="MSX Word">
    <type>Rom</type>
    <slotted> <ps>3</ps> <ss>1</ss> <page>0</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>2</page> </slotted>
    <slotted> <ps>3</ps> <ss>1</ss> <page>3</page> </slotted>
    <parameter name="filename">fs-4600_msxword.rom</parameter>
    <parameter name="mappertype">NATIONAL</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">fs-4600.sram</parameter>
  </device>

  <device id="MSX Kanji Driver">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>2</ss> <page>1</page> </slotted>
    <slotted> <ps>0</ps> <ss>2</ss> <page>2</page> </slotted>
    <parameter name="filename">fs-4600_kanjibasic.rom</parameter>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">fs-4600_kanjifont.rom</parameter>
  </device>

  <device id="Kanji ROM 12X12">
    <type>Kanji12</type>
    <parameter name="filename">fs-4600_kanjifont12.rom</parameter>
  </device>

  <device id="Memory Mapped FDC">
    <type>FDC</type>
    <slotted> <ps>3</ps> <ss>3</ss> <page>1</page> </slotted>
    <slotted> <ps>3</ps> <ss>3</ss> <page>2</page> </slotted>
    <parameter name="filename">fs-4600_disk.rom</parameter>
    <parameter name="type">National</parameter>
    <parameter name="brokenFDCread">false</parameter>
    <parameter name="drivename1">diska</parameter>
  </device>

  <device id="S1985">
    <type>S1985</type>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">V9938</parameter>
    <parameter name="vram">128</parameter>
  </device>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">fs-4600.cmos</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

</msxconfig>
