=== AquariusPower/openMSX/src/msxconfig.dtd
<!ELEMENT msxconfig (device)+>
<!ELEMENT device (type,slotted?,parameter+)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT slotted (page,ps,ss)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT ss (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
                    name CDATA #IMPLIED>

=== AquariusPower/openMSX/share/machines/National_CF-2700/hardwareconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">false</parameter>
  </config>

  <device id="Main RAM">
    <type>RAM</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>2</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>3</page> </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
  </device>

  <device id="MSX BIOS with BASIC ROM">
    <type>Rom</type>
    <slotted> <ps>0</ps> <ss>0</ss> <page>0</page> </slotted>
    <slotted> <ps>0</ps> <ss>0</ss> <page>1</page> </slotted>
    <parameter name="filename">roms/cf-2700_basic-bios1.rom</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">TMS99X8A</parameter>
  </device>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

  <config id="CassettePort">
  </config>

</msxconfig>

=== AquariusPower/openMSX/src/cfg/scc.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  <device id="Empty SCC Cartridge">
    <type>Rom</type>
    <slotted> <ps>1</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>1</ps> <ss>0</ss> <page>2</page> </slotted>
    <parameter name="volume">11500</parameter>
    <parameter name="mappertype">SCC</parameter>
  </device>
</msxconfig>

=== AquariusPower/openMSX/share/extensions/Panasonic_FS-CA1/hardwareconfig.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>


 <device id="MSX-Audio ROM">
    <type>Rom</type>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>0</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>1</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>2</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>3</page> </slotted>
    <parameter name="filename">FS-CA1.ROM</parameter>
    <parameter name="mappertype">MSX-AUDIO</parameter>
  </device>
  
</msxconfig>

=== AquariusPower/openMSX/src/cfg/someconfig.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  
  <config id="MotherBoard">
    <type>MotherBoard</type>
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">true</parameter>
  </config>
  
  <device id="myram1">
    <type>Simple64KB</type>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>0</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>2</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>3</ss>
      <page>3</page>
    </slotted>
    <parameter name="slow_drain_on_reset">true</parameter>
  </device>

  <device id="biosrom">
    <type>Rom16KB</type>
    <slotted>
      <page>0</page>
      <ps>0</ps>
      <ss>0</ss>
    </slotted>
    <parameter name="filename">MSX.ROM</parameter>
    <parameter name="skip_headerbytes">0</parameter>
  </device>
  
  <device id="basicrom">
    <type>Rom16KB</type>
    <slotted>
      <page>1</page>
      <ps>0</ps>
      <ss>0</ss>
    </slotted>
    <parameter name="filename">MSX.ROM</parameter>
    <parameter name="skip_headerbytes">16384</parameter>
  </device>

  <device id="diskrom">
    <type>Rom16KB</type>
    <slotted>
      <ps>3</ps>
      <ss>1</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">DISK.ROM</parameter>
    <parameter name="skip_headerbytes">0</parameter>
    <parameter name="0x0010" class="patch">0xED</parameter>
    <parameter name="0x0011" class="patch">0xFE</parameter>
    <parameter name="0x0012" class="patch">0xC9</parameter>
    <parameter name="0x0013" class="patch">0xED</parameter>
    <parameter name="0x0014" class="patch">0xFE</parameter>
    <parameter name="0x0015" class="patch">0xC9</parameter>
    <parameter name="0x0016" class="patch">0xED</parameter>
    <parameter name="0x0017" class="patch">0xFE</parameter>
    <parameter name="0x0018" class="patch">0xC9</parameter>
    <parameter name="0x001C" class="patch">0xED</parameter>
    <parameter name="0x001D" class="patch">0xFE</parameter>
    <parameter name="0x001E" class="patch">0xC9</parameter>
    <parameter name="0x001F" class="patch">0xED</parameter>
    <parameter name="0x0020" class="patch">0xFE</parameter>
    <parameter name="0x0021" class="patch">0xC9</parameter>
    <parameter name="" class="patchcode">MSXDiskRomPatch</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="foo_bug">no</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">TMS99X8A</parameter>
    <parameter name="limit_sprites">true</parameter>
  </device>

  <config id="renderer">
    <type>SDLLo</type>
    <parameter name="full_screen">false</parameter>
  </config>

<!--
  <device id="Turbo-R timer">
    <type>E6Timer</type>
  </device>
-->

  <device id="psg">
    <type>PSG</type>
  </device>

  <device id="Kanji ROM">
    <type>Kanji</type>
    <parameter name="filename">KANJI.ROM</parameter>
    <parameter name="skip_headerbytes">0</parameter>
  </device>

  <device id="Mapper IO">
    <type>MapperIO</type>
    <parameter name="type">Philips</parameter>
  </device>
<!--
  <device id="mymapper1">
    <type>MemoryMapper</type>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>2</page>
    </slotted>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>3</page>
    </slotted>
    <parameter name="slow_drain_on_reset">false</parameter>
    <parameter name="size">512</parameter>
  </device>
-->
  <device id="Real time clock">
    <type>RTC</type>
    <parameter name="mode">EmuTime</parameter>
  </device>

  <device id="Real time synchronizer">
    <type>RealTime</type>
  </device>
  
  <device id="Penguin Adventure Cartridge">
    <type>MegaRom</type>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>1</ps>
      <ss>0</ss>
      <page>2</page>
    </slotted>
    <parameter name="filename">PENGUIN.ROM</parameter>
    <parameter name="filesize">131072</parameter>
    <parameter name="skip_headerbytes">0</parameter>
  </device>

<!--
  <device id="FM PAC">
    <type>FM-PAC</type>
    <slotted>
      <ps>2</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">FMPAC.ROM</parameter>
    <parameter name="skip_headerbytes">0</parameter>
  </device>
-->
<!--
  <device id="MSX Music">
    <type>Music</type>
    <slotted>
      <ps>2</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">MUSIC.ROM</parameter>
    <parameter name="skip_headerbytes">0</parameter>
  </device>
-->
 
  <device id="cpu">
    <type>CPU</type>
  </device>
  
</msxconfig>

=== AquariusPower/openMSX/src/cfg/cbios-msx1.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>

  <config id="ExternalSlots">
    <parameter name="slota">1-0</parameter>
    <parameter name="slotb">2-0</parameter>
  </config>

  <config id="MotherBoard">
    <parameter name="0" class="subslotted">false</parameter>
    <parameter name="1" class="subslotted">false</parameter>
    <parameter name="2" class="subslotted">false</parameter>
    <parameter name="3" class="subslotted">false</parameter>
  </config>

  <device id="Main RAM">
    <type>RAM</type>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>2</page>
    </slotted>
    <slotted>
      <ps>3</ps>
      <ss>0</ss>
      <page>3</page>
    </slotted>
  </device>

  <device id="C-BIOS main">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>0</page>
    </slotted>
    <parameter name="filename">../Contrib/cbios/CB_MAIN.BIN</parameter>
  </device>

  <device id="C-BIOS second half">
    <type>Rom</type>
    <slotted>
      <ps>0</ps>
      <ss>0</ss>
      <page>1</page>
    </slotted>
    <parameter name="filename">../Contrib/cbios/CB_SH.BIN</parameter>
  </device>

  <device id="ppi">
    <type>PPI</type>
    <parameter name="volume">16000</parameter>
    <parameter name="key_ghosting">true</parameter>
  </device>

  <device id="VDP">
    <type>VDP</type>
    <parameter name="version">TMS99X8A</parameter>
  </device>

  <device id="psg">
    <type>PSG</type>
    <parameter name="volume">21000</parameter>
  </device>

  <device id="cpu">
    <type>CPU</type>
  </device>

  <device id="Printer Port">
    <type>PrinterPort</type>
  </device>

</msxconfig>

=== AquariusPower/openMSX/share/extensions/scc/hardwareconfig.xml
<?xml version="1.0" ?>
<!-- $Id$ --><!DOCTYPE msxconfig
  SYSTEM 'msxconfig.dtd'>
<msxconfig>
  <device id="Empty Konami SCC Cartridge">
    <type>ROM</type>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>1</page> </slotted>
    <slotted> <ps>-1</ps> <ss>-1</ss> <page>2</page> </slotted>
    <volume>11500</volume>
    <mappertype>SCC</mappertype>
  </device>
</msxconfig>

=== AquariusPower/openMSX/share/extensions/fmpac/hardwareconfig.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  <device id="FM PAC">
    <type>FM-PAC</type>
    <slotted><ps>-1</ps><ss>-1</ss><page>1</page></slotted>
    <parameter name="filename">roms/FMPAC.ROM</parameter>
    <parameter name="volume">13000</parameter>
    <parameter name="mode">mono</parameter>
    <parameter name="loadsram">true</parameter>
    <parameter name="savesram">true</parameter>
    <parameter name="sramname">FMPAC.PAC</parameter>
  </device>
</msxconfig>

=== AquariusPower/openMSX/src/cfg/scc+.xml
<?xml version="1.0"?>
<!DOCTYPE msxconfig SYSTEM "msxconfig.dtd">
<msxconfig>
  <device id="SCC+ Cartridge">
    <type>SCCPlusCart</type>
    <slotted> <ps>1</ps> <ss>0</ss> <page>1</page> </slotted>
    <slotted> <ps>1</ps> <ss>0</ss> <page>2</page> </slotted>
    <!--<parameter name="filename">NEMESIS2.ROM</parameter>-->
    <parameter name="volume">13000</parameter>
  </device>
</msxconfig>
