=== AquariusPower/openMSX/src/romdb.dtd
<!ELEMENT romdb (rom)+>
<!ELEMENT rom (md5+,romtype)>
<!ATTLIST rom
              id CDATA #IMPLIED>
<!ELEMENT md5 (#PCDATA)>
<!ELEMENT romtype (#PCDATA)>

=== AquariusPower/openMSX/src/romdb.xml
<?xml version="1.0"?>
<!-- $Id$ -->
<!DOCTYPE romdb SYSTEM "romdb.dtd">

<romdb>
  <rom id="Game Master 2">
    <md5>1fecd63cf4967dd6d2d4f6901d8d210b</md5>
    <romtype>GAMEMASTER2</romtype>
  </rom>
  <rom id="Bubbler">
    <md5>3c4113a49c1cbcefc0a73655f807691a</md5>
    <romtype>KONAMI5</romtype>
  </rom>
  <rom id="Painter">
    <md5>403cdea1cbd2bb24fae506941f8f655e</md5>
    <romtype>PLAIN</romtype>
  </rom>
  <rom id="Konami's Synthesizer">
    <md5>458365aa94bedcef0718207c7ecbcf85</md5>
    <romtype>SYNTHESIZER</romtype>
  </rom>
  <rom id="Konami Majutsushi">
    <md5>157948f839762dc9922e4011bb4dc9e6</md5>
    <romtype>MAJUTSUSHI</romtype>
  </rom>
  <rom id="Hydlide 2">
    <md5>4ad6b44220390d76e8565be2abcdadda</md5>
    <romtype>HYDLIDE2</romtype>
  </rom>
  <rom id="Xanadu">
    <md5>03e7119173912f9444cb96ed58ba4957</md5>
    <romtype>XANADU</romtype>
  </rom>
  <rom id="Royal Blood">
    <md5>6a1571a643e6c34837535a3240f85ef2</md5>
    <romtype>ROYALBLOOD</romtype>
  </rom>
  <rom id="Rastan Saga">
    <md5>114264bbcd0fdfa7bd083a983606a200</md5>
    <romtype>ASCII8</romtype>
  </rom>
</romdb>
